### ISSUE TITLE
[BUG] DateTimeAdd may fail with different localization

### ISSUE THREAD

**Issue by BernieWhite** [Azure/PSRule.Rules.Azure#2631]
### Description of the issue

As reported #2630.

Update the function to use the format string `M/d/yyyy h:mm:ss tt`.

### Error messages

```text
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.15]     PSRule.Rules.Azure.ExpressionBuilderTests.BuildExpressionWithDateTimeAdd [FAIL]
  Failed PSRule.Rules.Azure.ExpressionBuilderTests.BuildExpressionWithDateTimeAdd [< 1 ms]
  Error Message:
   Assert.Equal() Failure: Values differ
Expected: 4/7/2023 2:53:14 PM
Actual:   4/7/2023 2:53:14PM
  Stack Trace:
     at PSRule.Rules.Azure.ExpressionBuilderTests.BuildExpressionWithDateTimeAdd() in /Users/benji/PSRule.Rules.Azure/tests/PSRule.Rules.Azure.Tests/ExpressionBuilderTests.cs:line 122
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Reproduction

As reported #2630

### Version of PSRule

2.9.0

### Version of PSRule for Azure

1.32.1

**Comment by BernieWhite** [comment]
@BenjaminEngeset Are you able to report the output of `(Get-Culture).DateTimeFormat` in PowerShell from your machine. Thanks.

**Comment by BenjaminEngeset** [comment]
> @BenjaminEngeset Are you able to report the output of `(Get-Culture).DateTimeFormat` in PowerShell from your machine. Thanks.

```
PS /Users/benji/PSRule.Rules.Azure> (Get-Culture).DateTimeFormat

AMDesignator                     : AM
Calendar                         : System.Globalization.GregorianCalendar
DateSeparator                    : /
FirstDayOfWeek                   : Sunday
CalendarWeekRule                 : FirstDay
FullDateTimePattern              : dddd, MMMM d, yyyy h:mm:ss tt
LongDatePattern                  : dddd, MMMM d, yyyy
LongTimePattern                  : h:mm:ss tt
MonthDayPattern                  : MMMM d
PMDesignator                     : PM
RFC1123Pattern                   : ddd, dd MMM yyyy HH':'mm':'ss 'GMT'
ShortDatePattern                 : M/d/yyyy
ShortTimePattern                 : h:mm tt
SortableDateTimePattern          : yyyy'-'MM'-'dd'T'HH':'mm':'ss
TimeSeparator                    : :
UniversalSortableDateTimePattern : yyyy'-'MM'-'dd HH':'mm':'ss'Z'
YearMonthPattern                 : MMMM yyyy
AbbreviatedDayNames              : {Sun, Mon, Tue, Wed…}
ShortestDayNames                 : {Su, Mo, Tu, We…}
DayNames                         : {Sunday, Monday, Tuesday, Wednesday…}
AbbreviatedMonthNames            : {Jan, Feb, Mar, Apr…}
MonthNames                       : {January, February, March, April…}
IsReadOnly                       : True
NativeCalendarName               : Gregorian Calendar
AbbreviatedMonthGenitiveNames    : {Jan, Feb, Mar, Apr…}
MonthGenitiveNames               : {January, February, March, April…}
```
